Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "9p", mount_options: ['trans=virtio']

  # Server Node
  config.vm.define "cpeset-cS", primary: true do |server|
    server.vm.hostname = "cpeset-cS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider :libvirt do |v|
      v.memory = 512
      v.cpus = 1
    end

    server.vm.provision "shell", path: "provision/install-deps.sh"
    server.vm.provision "shell", path: "provision/install-k3s-server.sh"

  end

  # Worker Node
  config.vm.define "cpeset-cSW" do |worker|
    worker.vm.hostname = "cpeset-cSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider :libvirt do |v|
      v.memory = 512
      v.cpus = 1
    end

    worker.vm.provision "shell", path: "provision/install-deps.sh"
    worker.vm.provision "shell", path: "provision/install-k3s-worker.sh"

  end
end
